# Plateforme Agnostique de Traitement et d'Analyse des Textes
### Carnet d'expérimentation
---

## Sujet : Hugging Face

---

## Observations et environnement
---

In [1]:
cd ../..

/Users/fm/Desktop/Work/Patat


In [2]:
import importlib
import pandas as pd

### Chargement des données

In [3]:
article_filename = 'data/demo/221008-Article.csv'

import patat.db.article_db

article_db = patat.db.article_db.ArticleDb(article_filename)

article_db.df()

url  \
0      https://reseauinternational.net/tous-les-jeune...   
1      https://reseauinternational.net/adhesion-a-la-...   
2      https://lemediaen442.fr/onu-le-premier-ministr...   
3      https://www.francesoir.fr/societe-environnemen...   
4      https://www.breizh-info.com/2022/09/27/208410/...   
...                                                  ...   
87179  https://www.profession-gendarme.com/zelensky-e...   
87180  https://www.profession-gendarme.com/zelensky-l...   
87181  https://www.profession-gendarme.com/zelensky-m...   
87182  https://www.profession-gendarme.com/zero-mort-...   
87183  https://www.profession-gendarme.com/zoom-franc...   

                                                   title  \
0            Tous les jeunes, portez la nouvelle (russe)   
1      Adhésion à la Russie : 93% pour le « oui » dan...   
2      ONU – Le Premier ministre de Nouvelle-Zélande ...   
3      Compostage humain: les “funérailles vertes” ga...   
4                    Donatello : génie de la Renaissance   
...                                                  ...   
87179  Zelensky est « une marionnette qui fait inutil...   
87180  Zélensky : l’arnaque de la contre-offensive uk...   
87181  Zelensky massacre maintenant des citoyens ukra...   
87182  Zéro mort du coronavirus : comment expliquer l...   
87183  Zoom – Francis Cousin : « La grande explosion ...   

                                                 article  \
0      par Pepe Escobar.\nL’OCS à Samarcande et l’Ass...   
1      Dans les régions de Zaporijia et de Kherson, 9...   
2      L’argument principal de la ministre est que le...   
3      Aux États-Unis, les différents gouvernements r...   
4      Portrait du sculpteur Donatello (1386-1466), p...   
...                                                  ...   
87179  Encore un journaliste surpris qu’un colonel am...   
87180  Le président Zelensky et ses alliés de l’Otan ...   
87181  ZELENSKY A ORDONNÉ QUE TOUTES LES PERSONNES FU...   
87182  Le Vietnam est une exception dans le monde : a...   
87183  Francis Cousin, docteur en philosophie, annonc...   

                              site                 author  \
0          reseauinternational.net                    NaN   
1          reseauinternational.net                    NaN   
2                  lemediaen442.fr                    NaN   
3                www.francesoir.fr  Auteur(s)\nFranceSoir   
4              www.breizh-info.com                    NaN   
...                            ...                    ...   
87179  www.profession-gendarme.com                    NaN   
87180  www.profession-gendarme.com                    NaN   
87181  www.profession-gendarme.com                    NaN   
87182  www.profession-gendarme.com                    NaN   
87183  www.profession-gendarme.com                    NaN   

                  date_iso                                     url_h  
0      2022-09-30T00:00:00  f95a294c94ff76cc9626ae06300a8b38067f89cf  
1      2022-09-30T00:00:00  c924dab7ded47578d81c3ae46f8be0964b3c50f1  
2      2022-09-29T00:00:00  3d47a59ef99274fd9ee96c209cc2ab41d6e1f6bb  
3      2022-09-28T13:15:00  0c0341a1f5fae820ee307cb54024df6b06a93d85  
4      2022-09-27T00:00:00  fcce819327d0302c4cf5e3a8a43b54327ffb8e63  
...                    ...                                       ...  
87179                  NaN  e346761c2a99d892b26c9388480e0ee6ad6b303b  
87180                  NaN  77525354644316eadab53960efa8f5fd028c7f67  
87181                  NaN  fc6a074da5c02032bc9fc3f35f1044bc4029042c  
87182                  NaN  e4f0a8961d79c9a5f66c80d7aa4196cb679af2b0  
87183                  NaN  36a0091795b15d56005a6b7b8963ada539f598eb  

[87184 rows x 7 columns]

## Expérience
---

### Etape 1

In [4]:
from transformers import pipeline


import torch
import torch.nn.functional as F

In [5]:
model_name = 'distilbert-base-uncased-finetuned-sst-2-english'

classifier = pipeline('sentiment-analysis', model=model_name)
results = classifier([
    'We are very happy to show you the Transformers Library',
    'Whe hope you don\'t hate it',
])
results

[{'label': 'POSITIVE', 'score': 0.9998044371604919},
 {'label': 'NEGATIVE', 'score': 0.5178766250610352}]

In [6]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [7]:
model = AutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [8]:
classifier = pipeline('sentiment-analysis', model=model, tokenizer=tokenizer)
results = classifier([
    'We are very happy to show you the Transformers Library',
    'Whe hope you don\'t hate it',
])
results

[{'label': 'POSITIVE', 'score': 0.9998044371604919},
 {'label': 'NEGATIVE', 'score': 0.5178766250610352}]

In [9]:
tokenizer.tokenize('We are very happy to show you the Transformers Library')

['we',
 'are',
 'very',
 'happy',
 'to',
 'show',
 'you',
 'the',
 'transformers',
 'library']

In [10]:
tokenizer('We are very happy to show you the Transformers Library')

{'input_ids': [101, 2057, 2024, 2200, 3407, 2000, 2265, 2017, 1996, 19081, 3075, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [11]:
X_train = [
    'We are very happy to show you the Transformers Library',
    'Whe hope you don\'t hate it',
]

In [12]:
batch = tokenizer(X_train, padding=True, truncation=True, max_length=512, return_tensors='pt')

In [13]:
with torch.no_grad():
    outputs = model(**batch)
    print(outputs)
    predictions = F.softmax(outputs.logits,dim=1)
    print(predictions)
    labels = torch.argmax(predictions, dim=1)
    print(labels)
    labels = [model.config.id2label[label_id] for label_id in labels.tolist()]
    print(labels)

SequenceClassifierOutput(loss=None, logits=tensor([[-4.1465e+00,  4.3928e+00],
        [ 6.8991e-02, -2.5465e-03]]), hidden_states=None, attentions=None)
tensor([[1.9560e-04, 9.9980e-01],
        [5.1788e-01, 4.8212e-01]])
tensor([1, 0])
['POSITIVE', 'NEGATIVE']


In [14]:
predictions

tensor([[1.9560e-04, 9.9980e-01],
        [5.1788e-01, 4.8212e-01]])

In [15]:
import torch.nn

In [16]:
import torch.nn.functional as F

In [19]:
from transformers import AutoTokenizer, AutoModelForTokenClassification

tokenizer = AutoTokenizer.from_pretrained("Jean-Baptiste/camembert-ner")
model = AutoModelForTokenClassification.from_pretrained("Jean-Baptiste/camembert-ner")


##### Process text sample (from wikipedia)

from transformers import pipeline

nlp = pipeline('ner', model=model, tokenizer=tokenizer, aggregation_strategy="simple")
nlp("Apple est créée le 1er avril 1976 dans le garage de la maison d'enfance de Steve Jobs à Los Altos en Californie par Steve Jobs, Steve Wozniak et Ronald Wayne14, puis constituée sous forme de société le 3 janvier 1977 à l'origine sous le nom d'Apple Computer, mais pour ses 30 ans et pour refléter la diversification de ses produits, le mot « computer » est retiré le 9 janvier 2015.")



TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

In [18]:
!pip install protobuf


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 484.0/484.0 kB 3.2 MB/s eta 0:00:0000:0100:01


In [20]:
from transformers import AutoTokenizer, AutoModelForTokenClassification
from transformers import pipeline
tokenizer = AutoTokenizer.from_pretrained("Davlan/bert-base-multilingual-cased-ner-hrl")
model = AutoModelForTokenClassification.from_pretrained("Davlan/bert-base-multilingual-cased-ner-hrl")
nlp = pipeline("ner", model=model, tokenizer=tokenizer)
example = "Nader Jokhadar had given Syria the lead with a well-struck header in the seventh minute."
ner_results = nlp(example)
print(ner_results)

Downloading:   0%|          | 0.00/264 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.10k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/996k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/709M [00:00<?, ?B/s]

[{'entity': 'B-PER', 'score': 0.9997156, 'index': 1, 'word': 'Nad', 'start': 0, 'end': 3}, {'entity': 'I-PER', 'score': 0.9816159, 'index': 2, 'word': '##er', 'start': 3, 'end': 5}, {'entity': 'I-PER', 'score': 0.99977404, 'index': 3, 'word': 'Jo', 'start': 6, 'end': 8}, {'entity': 'I-PER', 'score': 0.9998016, 'index': 4, 'word': '##kha', 'start': 8, 'end': 11}, {'entity': 'I-PER', 'score': 0.9997688, 'index': 5, 'word': '##dar', 'start': 11, 'end': 14}, {'entity': 'B-LOC', 'score': 0.99973196, 'index': 8, 'word': 'Syria', 'start': 25, 'end': 30}]


In [23]:
text = article_db.df()['article'][0]

In [27]:
text

'par Pepe Escobar.\nL’OCS à Samarcande et l’Assemblée générale des Nations unies ont démontré que la quasi-totalité des pays du Sud hors de l’OTANistan, ne diabolisent pas la Russie.\nLes plaques tectoniques géopolitiques se déplacent et se balancent, et le son est entendu dans le monde entier, alors que les petits oursons jumeaux, la RPD et la RPL, ainsi que Kherson et Zaporijia, votent pour leurs référendums. Fait irrémédiable : à la fin de la semaine prochaine, la Russie sera très certainement en passe d’ajouter plus de 100 000 km2 et plus de 5 millions de personnes à la Fédération.\nDenis Pouchiline, chef de la RPD, a résumé la situation : « Nous rentrons à la maison ». Les bébés ours rentrent chez Maman.\nSi l’on ajoute à cela la mobilisation partielle de près de 300 000 réservistes russes – qui n’est sans doute qu’une première phase – les conséquences de cette mobilisation sont immenses. Exit le précédent format souple de l’opération militaire spéciale (OMS) : entrez dans une gue

In [26]:
ner_results = nlp(text)
for ne in ner_results:
    print (ne['word'])

Pepe
Escobar
O
##CS
Sama
##rca
##nde
Assemblée
générale
des
Nations
unie
Russie
RP
##D
RP
##L
K
##hers
##on
Za
##por
##iji
##a
Russie
Fédération
Denis
Po
##uchi
##line
RP
##D
Mama
##n
Chine
OTAN
The
Economist
Kr
##emlin
Po
##uti
##ne


## Mesure et observation des résultats
---

## Sauvegarde des résultats
---

## Conclusions
---

- Résultat : OK

## Bricolages
---