# Plateforme Agnostique de Traitement et d'Analyse des Textes
### Carnet d'expérimentation
---

## Sujet : Entrainement Recueil+AFP

---

# Observations et environnement
---

In [1]:
cd ../..

/Users/fm/Desktop/Work/Patat


In [2]:
import importlib
import pandas as pd
import seaborn as sns

## Paramètres globaux

In [ ]:
random_state = 42

## Labels et Articles

In [3]:
import patat.db.label_db

In [4]:
importlib.reload(patat.db.label_db)
label_filename = ''

label_db = patat.db.label_db.LabelDb(label_filename)
label_db.df()

url  label     value  \
0       https://www.francesoir.fr/lifestyle-gastronomi...  infox  0.000000   
1       https://www.francetvinfo.fr/replay-radio/franc...  infox  0.000000   
2       https://fr.novopress.info/219709/vous-regardez...  infox  0.000000   
3       https://fr.sott.net/article/39833-Hubble-confi...  infox  0.000000   
4       https://www.francesoir.fr/lifestyle-shopping/f...  infox  0.000000   
...                                                   ...    ...       ...   
265105  https://www.profession-gendarme.com/zelensky-e...  infox  0.556761   
265106  https://www.profession-gendarme.com/zelensky-l...  infox  0.164531   
265107  https://www.profession-gendarme.com/zelensky-m...  infox  0.673791   
265108  https://www.profession-gendarme.com/zero-mort-...  infox  0.103192   
265109  https://www.profession-gendarme.com/zoom-franc...  infox  0.303205   

                               owner  type  \
0       francois.bancilhon@gmail.com   obs   
1       francois.bancilhon@gmail.com   obs   
2       francois.bancilhon@gmail.com   obs   
3       francois.bancilhon@gmail.com   obs   
4       francois.bancilhon@gmail.com   obs   
...                              ...   ...   
265105               220930-tf_lr.pp  pred   
265106               220930-tf_lr.pp  pred   
265107               220930-tf_lr.pp  pred   
265108               220930-tf_lr.pp  pred   
265109               220930-tf_lr.pp  pred   

                                           url_h  
0       34a9c70d8ec4accc4b752c593bdf44908a4a4918  
1       9660258c54f2a9c83ccbf9cd374dcb52ea831a77  
2       3a1a42c8fbf323dd0a2b69aaa721cc24c8886588  
3       645c3f6c815ce0a0283850d4ed47756c80be4744  
4       11dff6919bbc94894c7d31a6480ae7a19ab9ebd7  
...                                          ...  
265105  e346761c2a99d892b26c9388480e0ee6ad6b303b  
265106  77525354644316eadab53960efa8f5fd028c7f67  
265107  fc6a074da5c02032bc9fc3f35f1044bc4029042c  
265108  e4f0a8961d79c9a5f66c80d7aa4196cb679af2b0  
265109  36a0091795b15d56005a6b7b8963ada539f598eb  

[265110 rows x 6 columns]

In [5]:
import patat.db.article_db

In [6]:
importlib.reload(patat.db.article_db)
article_filename = ''

article_db = patat.db.article_db.ArticleDb(article_filename)
article_db.df()

/Users/fm/Desktop/Work/Patat/patat/db/article_db.py:35: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)


url  \
0      https://ripostelaique.com/pour-des-controles-a...   
1      https://ripostelaique.com/le-wokisme-cest-la-s...   
2      https://ripostelaique.com/ce-que-cache-la-fron...   
3      https://ripostelaique.com/motion-de-censure-ra...   
4      https://ripostelaique.com/jordan-bardella-et-l...   
...                                                  ...   
86771  https://www.lelibrepenseur.org/une-histoire-vi...   
86772              https://www.lelibrepenseur.org/actus/   
86773  https://www.lelibrepenseur.org/affiche-des-dec...   
86774         https://www.lelibrepenseur.org/communaute/   
86775  https://www.lelibrepenseur.org/utilisation-des...   

                                                   title  \
0      Pour des contrôles au faciès pour nous préserv...   
1      Le wokisme, c’est la suite du communisme pour ...   
2      Ce que cache la fronde des policiers contre la...   
3      Motion de censure : Rachid Méluche et Marine s...   
4      Jordan Bardella et le redressement de la Franc...   
...                                                  ...   
86771              Une histoire vieille comme le monde !   
86772                                              Actus   
86773  Affiche des décès et malaises de sportifs de h...   
86774                                         Communauté   
86775             Utilisation des cookies sur notre site   

                                                 article  \
0      La gauche souhaite que les clandestins qui dé...   
1      Intervention d’Emmanuel Albach lors du Rendez-...   
2      La police dans la rue pour protester contre le...   
3      Bon c’est pas le tout, mais le cirque continue...   
4      Sa jeunesse et sa verve sur un ton clair et un...   
...                                                  ...   
86771  Certains veulent des preuves ! Ils ont raison....   
86772  Dernière vidéo !\nIl était temps, enfin ! Je v...   
86773  Un nombre inquiétant de sportifs de haut nivea...   
86774  Notre Réseau Telegram et ses Groupes Secondair...   
86775  Que sont les cookies ?\n\n\nLes cookies sont d...   

                      author                       tag  abstract  \
0              Pierre Cassen        ['RIPOSTE LAIQUE']       NaN   
1            Emmanuel Albach  ['NOUVEL ORDRE MONDIAL']       NaN   
2              Josiane Filio        ['RIPOSTE LAIQUE']       NaN   
3             Paul Le Poulpe    ['HUMOUR ET DERISION']       NaN   
4      Lucien Samir Oulahbib          ['POINT DE VUE']       NaN   
...                      ...                       ...       ...   
86771             Par\nAdmin                       NaN       NaN   
86772              Par\nuser                       NaN       NaN   
86773                    NaN                       NaN       NaN   
86774                    NaN                       NaN       NaN   
86775                    NaN                       NaN       NaN   

                         site             date_iso  \
0           ripostelaique.com  2022-11-06T00:00:00   
1           ripostelaique.com  2022-10-23T00:00:00   
2           ripostelaique.com  2022-10-11T00:00:00   
3           ripostelaique.com  2022-10-20T00:00:00   
4           ripostelaique.com  2022-11-06T00:00:00   
...                       ...                  ...   
86771  www.lelibrepenseur.org  2010-05-04T00:00:00   
86772  www.lelibrepenseur.org  2007-07-07T00:00:00   
86773  www.lelibrepenseur.org                  NaN   
86774  www.lelibrepenseur.org                  NaN   
86775  www.lelibrepenseur.org                  NaN   

                                          url_h  c_count  
0      b48e9dec4ebfd6ec9dd7509e3082af29a29f8629     1177  
1      b0439a1d6022674542c2d41091d810173adfbeb9      438  
2      4cb608ae6a65db867d3238131fdf82b7f4119dd6    10200  
3      5cd5f3388084d7b64f22493bcce722768d65ff0e     3202  
4      f3315e30884c7ac3264570311ecf2b855aae95b4    16917  
...                                         ...      ...  
86771  8c7a

In [7]:
article_db.df().value_counts('site')

site
www.francesoir.fr              18452
www.francetvinfo.fr            14597
www.breizh-info.com             6070
www.dreuz.info                  5143
www.legorafi.fr                 4488
www.wikistrike.com              3897
www.profession-gendarme.com     3193
actu.fr                         2874
www.lelibrepenseur.org          2616
fr.sott.net                     2602
lesmoutonsrebelles.com          2174
lezarceleurs.blogspot.com       2131
www.alnas.fr                    2008
lemediaen442.fr                 1876
www.cnews.fr                    1519
www.anguillesousroche.com       1453
www.preuvesduparanormal.fr      1295
www.medias-presse.info          1151
reseauinternational.net         1147
ripostelaique.com               1058
theconversation.com             1049
www.lesalonbeige.fr              994
www.bvoltaire.fr                 967
lecourrier-du-soir.com           879
lesakerfrancophone.fr            872
www.polemia.com                  626
fr.novopress.info                

# Experience
---

## Données d'entrainement

### Recueil

In [8]:
df_labels = label_db.df()

In [9]:
df_labels = df_labels[df_labels['owner']=='recueil']

In [10]:
df_labels = df_labels[df_labels['label']=='infox'][['url','value']]

In [11]:
df_labels = df_labels.rename(columns={'value':'infox'})

In [12]:
df_labels

url  infox
98     https://www.alnas.fr/actualite/communaute/lara...    0.0
120    https://www.alnas.fr/actualite/en-vrac/quel-ar...    0.0
142    https://www.alnas.fr/actualite/politique/laust...    0.0
164    https://www.alnas.fr/actualite/communaute/nant...    0.0
186    https://www.alnas.fr/actualite/en-vrac/la-fran...    0.0
...                                                  ...    ...
10718  https://www.wikistrike.com/2022/09/les-command...    1.0
10739  https://www.wikistrike.com/2022/09/coupures-el...    1.0
10760  https://www.wikistrike.com/2022/09/11-septembr...    1.0
10781  https://www.wikistrike.com/2022/10/selon-un-an...    1.0
10803  https://www.wikistrike.com/2022/10/la-pologne-...    1.0

[536 rows x 2 columns]

In [13]:
df_corpus = article_db.df()

In [14]:
df_corpus['text'] = df_corpus['title']+'\n'+df_corpus['article']

In [15]:
df_corpus=df_corpus[['url','text']]

In [16]:
df_texts = pd.merge(df_corpus,df_labels)

In [17]:
df_texts.to_csv('data/tmp/221118-TextsInfox.csv',index=False)

### AFP

In [18]:
df_corpus = article_db.df()

In [19]:
import patat.util.text

In [20]:
importlib.reload(patat.util.text)

<module 'patat.util.text' from '/Users/fm/Desktop/Work/Patat/patat/util/text.py'>

In [21]:
df_corpus['site']=df_corpus['url'].apply(patat.util.text.get_site_from_url)

In [22]:
def is_afp(text):
    if type(text)==str:
        return 'afp' in text.lower()
    return False
    

In [23]:
df_afp = df_corpus[(df_corpus['site']=='www.francesoir.fr')&(df_corpus['author'].apply(is_afp))]

In [24]:
df_afp_texts = df_afp[['url','text']].copy()

In [25]:
df_afp_texts['infox']=0.0

In [143]:
df_afp_texts.to_csv('data/tmp/221118-TextsAfp.csv',index=False)

In [27]:
df_texts

url  \
0    https://ripostelaique.com/oui-la-russie-doit-e...   
1    https://ripostelaique.com/georgia-meloni-rafle...   
2    https://ripostelaique.com/grande-bretagne-davo...   
3    https://www.medias-presse.info/pelerinage-de-l...   
4    https://www.medias-presse.info/contrat-secret-...   
..                                                 ...   
485  https://www.lelibrepenseur.org/sanna-marine-la...   
486  https://www.lelibrepenseur.org/manifestations-...   
487  https://www.lelibrepenseur.org/les-deces-exces...   
488  https://www.lelibrepenseur.org/1-milliard-de-c...   
489  https://www.lelibrepenseur.org/bill-gates-cont...   

                                                  text  infox  
0    Oui, la Russie va faire tomber cette Europe po...    0.0  
1    Georgia Meloni rafle la mise : un grand bravo ...    0.0  
2    Grande-Bretagne: Davos prend ouvertement le po...    1.0  
3    Pèlerinage de la FSSPX à Lourdes : certains gr...    0.0  
4    Contrat secret entre Pfizer et von der Leyen :...    1.0  
..                                                 ...    ...  
485  Sanna Marin, la Première ministre finlandaise,...    0.0  
486  Manifestations importantes d’agriculteurs aux ...    1.0  
487  Les décès excessifs sont en augmentation mais ...    1.0  
488  1 milliard de Chinois touchés par un piratage ...    1.0  
489  Bill Gates continue de manipuler l’OMS avec se...    1.0  

[490 rows x 3 columns]

## Pipeline

### Preprocessor

In [28]:
import patat.util.text

importlib.reload(patat.util.text)
preprocessor = patat.util.text.get_latin
#preprocessor=None

### Tokenizer

In [29]:
from nltk.tokenize import word_tokenize, wordpunct_tokenize, sent_tokenize
from patat.ml.lex_analyser import LexAnalyser

lex = LexAnalyser()

tokenizer = lex.get_lemmas_from_text
#tokenizer = toklematize
#tokenizer = word_tokenize
#tokenizer = lex.get_words

### Ignore words

In [30]:
with open('data/tmp/221110-IgnoreLemmas.txt','r') as file:
    ignore_words = file.read().split()

In [31]:
ignore_words

['de',
 'la',
 'le',
 'les',
 'et',
 'des',
 'en',
 'un',
 'du',
 'est',
 'une',
 'que',
 'être',
 'avoir',
 'pour',
 'dans',
 'qui',
 'il',
 'par',
 'sur',
 'au',
 'pas',
 'ce',
 'plaire',
 'faire',
 'ne',
 'qu',
 'pouvoir',
 'se',
 'avec',
 'tout',
 'ou',
 'été',
 'son',
 'mais',
 'aux',
 'cette',
 'on',
 'nous',
 'comme',
 'elle',
 'même',
 'autre',
 'devoir',
 'ces',
 'pays',
 'leur',
 'si',
 'sa',
 'ses',
 'bien',
 'état',
 'contre',
 'ils',
 'vous',
 'sans',
 'voir',
 'je',
 'après',
 'deux',
 'depuis',
 'mettre',
 'russie',
 'monde',
 'entre',
 'grand',
 'an',
 'dire',
 'covid',
 'invitant',
 'guéguen',
 'patiemment',
 'méditation',
 'eda',
 'perdurer',
 'inversement',
 'guedj',
 'penn',
 'kang',
 'officieux',
 'jurisprudence',
 'kant',
 'hectare',
 'islamisation',
 'hebdo',
 'guichard',
 'entente',
 'guihard',
 'pepe',
 'duel',
 'haïr',
 'naufrage',
 'ironiquement',
 'olivennes',
 'juvénile',
 'inégal',
 'patois',
 'justifiant',
 'echos',
 'jacky',
 'economist',
 'géologique',


### TfIdfVectorizer

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [114]:
afp_size = 10
df_ml = pd.concat([df_texts,df_afp_texts.sample(afp_size,random_state=random_state)])

In [115]:
%%time
vectorizer = TfidfVectorizer(lowercase=True, preprocessor=preprocessor, tokenizer=tokenizer, stop_words=ignore_words)
#vectorizer = CountVectorizer(lowercase=True, preprocessor=preprocessor, tokenizer=tokenizer, stop_words=ignore_words)
count_matrix = vectorizer.fit_transform(df_ml['text'])
count_array = count_matrix.toarray()
df_tf = pd.DataFrame(data=count_array,columns = vectorizer.get_feature_names_out())
df_tf.shape

df_X = df_tf

len(df_X.keys())

/Users/fm/opt/anaconda3/lib/python3.9/site-packages/sklearn/feature_extraction/text.py:404: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['aboutir', 'abrutir', 'ambitieux', 'bouillir', 'coordonner', 'croire', 'décombrer', 'démoraliser', 'déplaire', 'désordonner', 'florir', 'joindre', 'matcher', 'maudire', 'menacer', 'mol', 'oxygéner', 'personnaliser', 'presser', 'précieux', 'présumer', 'recroître', 'saisir', 'satisfaire', 'subventionner', 'teindre', 'tracter', 'émerger', 'énoncer', 'équivaloir'] not in stop_words.
  warnings.warn(


CPU times: user 323 ms, sys: 5.73 ms, total: 329 ms
Wall time: 327 ms


9428

### Entrainement sklearn

In [116]:
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn import metrics

In [117]:
X = df_X
y=df_ml['infox']

In [118]:
df_X.shape

(500, 9428)

#### Initialisations

In [119]:
train_size=0.8
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=random_state,train_size=train_size)

#### Dummy Classifier

In [142]:
from sklearn.dummy import DummyClassifier
strategies = ['most_frequent', 'prior', 'stratified', 'uniform']
print(f'Test size: {len(y_test)} = {int(len(y_test)-y_test.sum())}x0 + {int(y_test.sum())}x1' )
for strategy in strategies:
    print('---------------')
    print(f'Strategy : {strategy}')
    classifier = DummyClassifier(strategy=strategy, random_state=random_state)
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    print(f'Accuracy score {metrics.accuracy_score(y_test, y_pred)*100:.2f}%')
    print(f'Recall score {metrics.recall_score(y_test, y_pred)*100:.2f}%')
    print(f'F1 score {metrics.f1_score(y_test, y_pred)*100:.2f}%')
    print('Matrice de confusion')
    cnf_matrix = metrics.confusion_matrix(y_test, y_pred,normalize='all')
    print(cnf_matrix)

Test size: 100 = 53x0 + 47x1
---------------
Strategy : most_frequent
Accuracy score 53.00%
Recall score 0.00%
F1 score 0.00%
Matrice de confusion
[[0.53 0.  ]
 [0.47 0.  ]]
---------------
Strategy : prior
Accuracy score 53.00%
Recall score 0.00%
F1 score 0.00%
Matrice de confusion
[[0.53 0.  ]
 [0.47 0.  ]]
---------------
Strategy : stratified
Accuracy score 49.00%
Recall score 44.68%
F1 score 45.16%
Matrice de confusion
[[0.28 0.25]
 [0.26 0.21]]
---------------
Strategy : uniform
Accuracy score 45.00%
Recall score 51.06%
F1 score 46.60%
Matrice de confusion
[[0.21 0.32]
 [0.23 0.24]]


#### Confusion Matrix
||Pred 0|Pred 1|
|---|---|---|
|Test 0|True Negative|False Positive|
|Test 1|False Negative|True Positive|

#### LogisticRegression

In [141]:
%%time
max_iter=500
#C=0.40
C=1000
solver = 'lbfgs'
classifier = LogisticRegression(C=C, random_state=random_state, solver=solver, max_iter=max_iter)

classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

print(f'Test size: {len(y_test)} = {int(len(y_test)-y_test.sum())}x0 + {int(y_test.sum())}x1' )
print(f'Accuracy score {metrics.accuracy_score(y_test, y_pred)*100:.2f}%')
print(f'Recall score {metrics.recall_score(y_test, y_pred)*100:.2f}%')
print(f'F1 score {metrics.f1_score(y_test, y_pred)*100:.2f}%')
cnf_matrix = metrics.confusion_matrix(y_test, y_pred,normalize='all')
print('Matrice de confusion')
print(cnf_matrix)

Test size: 100 = 53x0 + 47x1
Accuracy score 76.00%
Recall score 68.09%
F1 score 72.73%
Matrice de confusion
[[0.44 0.09]
 [0.15 0.32]]
CPU times: user 1.53 s, sys: 495 ms, total: 2.02 s
Wall time: 272 ms


In [124]:
# Cross validation
max_iter=500
#C=0.40
C=1000
solver = 'lbfgs'
random_state = 42
classifier = LogisticRegression(C=C, random_state=random_state, solver=solver, max_iter=max_iter)
scores = cross_val_score(classifier, X, y, cv=5,scoring='recall')
print(scores)
print(f'Mean Score : {scores.mean()*100:.2f}%')
print(f'Deviation Score : {scores.std()*100:.2f}%')


[0.70212766 0.70833333 0.64583333 0.83333333 0.6875    ]
Mean Score : 71.54%
Deviation Score : 6.29%


#### MLPClassifier

In [125]:
alpha=1e-4
hidden_layer_sizes=(256,64)
solver = 'lbfgs'
random_state = 42
classifier = MLPClassifier(solver='lbfgs', alpha=alpha, hidden_layer_sizes=hidden_layer_sizes, random_state=random_state)


In [140]:
%%time
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=random_state,train_size=0.8)

# Preprocessing of training data, fit model 
classifier.fit(X_train, y_train)

# Preprocessing of validation data, get predictions
y_pred = classifier.predict(X_test)
print(f'Test size: {len(y_test)} = {int(len(y_test)-y_test.sum())}x0 + {int(y_test.sum())}x1' )
print(f'Accuracy score {metrics.accuracy_score(y_test, y_pred)*100:.2f}%')
print(f'Recall score {metrics.recall_score(y_test, y_pred)*100:.2f}%')
print(f'F1 score {metrics.f1_score(y_test, y_pred)*100:.2f}%')
cnf_matrix = metrics.confusion_matrix(y_test, y_pred,normalize='all')
print('Matrice de confusion')
print(cnf_matrix)

Test size: 100 = 53x0 + 47x1
Accuracy score 76.00%
Recall score 68.09%
F1 score 72.73%
Matrice de confusion
[[0.44 0.09]
 [0.15 0.32]]
CPU times: user 1.61 s, sys: 369 ms, total: 1.98 s
Wall time: 274 ms


In [136]:
y_test.sum()

47.0

In [99]:
%%time
cv = cross_val_score(classifier, X, y, cv=5)
print(f'Mean CV Score : {cv.mean()*100:.2f}%')
print(cv)

Mean CV Score : 76.67%
[0.71568627 0.78431373 0.78431373 0.78431373 0.76470588]
CPU times: user 10min 49s, sys: 6min 6s, total: 16min 56s
Wall time: 1min 50s


# Sauvegarde des résultats
---

# Conclusions
---

- 

# Bricolages
---